- .eleventy.js
- package-lock.json
- package.json
- script/build
- script/develop
This allows to add images in the source directory 11ty will deploy them without restarting script/develop.
> Use 11ty to deploy images/resources

- src/_includes/guide.html
- src/support.html
Make sure at least 1 item is opened of the FAQ on load.
> Always expand a FAQ item

- src/documentation.html
- src/guides/find-a-cm4.html
https://deploy-preview-85--home-assistant-yellow.netlify.app/guides/find-a-cm4/
> Add a guide how to find a CM4

- src/procedures/procedures.11tydata.yaml
Add line about checking CM4 after heat sink is secured.
> Add line about checking CM4

- src/_includes/base.liquid
Added a Buy Dialog for the Yellow to replace the link to CrowdSupply
It's added in a pretty hacky and ugly way. I hope it's okay in the light of preparing a Marketing page anyways.
> Buy Dialog for the Yellow

- src/faq.html
> Add FAQ item on battery replacement

- src/procedures/procedures.11tydata.yaml
- Add video showing how to install the CM4 on Home Assistant Yellow
> Add video to install CM4 step

- src/faq.html
> Move list of unsupported NVMe SSDs into separate FAQ item

- src/faq.html
I will add a procedure describing how to check if the CM4 is seated correctly in a separate pull request later on.
@cogneato, @jacquelineraaflaub: Does this cover the steps you mentioned yesterday? Let me know if I should add/change anything.
> Add FAQ item on unreachable Yellow

- src/procedures/procedures.11tydata.yaml
> Fix typo in NVMe

- src/documentation.html
- add an additional section to help readers find content more quickly.
> Add multiprotocol section to docu page

- src/guides/about-multiprotocol.html
- to match content provided in SkyConnect documentation
> Improve description of channel conflict resolution

- src/faq.html
- linking to About multiprotocol, as the conflict resolution is described in more detail there
> Multiprotocol: Add FAQ item on channel conflict resolution

- public/pinion/v1.2-standard/spec.json
- public/pinion/v1.3-poe/spec.json
- public/pinion/v1.3-standard/spec.json
- Fixes broken links for serial console
- Updates wording to reflect Linux/macOS
> update serial console links

- src/guides/about-multiprotocol.html
- src/procedures/procedures.11tydata.yaml
- The cogwheel on the integration card was removed in 2023.7
> Integration page: remove references to cogwheel

- src/_includes/base.liquid
- src/documentation.html
- src/guides/install-yellow-light-keeps-flashing-in-heartbeat.html
- Symptom: yellow LED keeps blinking, installation fails
> Add troubleshooting topic on Yellow kit installation

- src/_includes/base.liquid
- src/index.html
- Add links to Home Assistant and NC websites
- Fix typo on landing page
> Add links to Home Assistant and NC websites

- src/_includes/style.css
- src/documentation.html
Add multiprotocol subtitle
- to make it clearer what the multiprotocol is about
> Add subtitle to make it clearer what multiprotocol is

- src/procedures/procedures.11tydata.yaml
These were confusing me while setting up my Yellow. (I _assume_ these are correct, AFAICT; I haven't actually finished setting up the Yellow :grin:)
Note that I couldn't test these patches because I couldn't figure out how to build this repository - there was no e.g. `prepare` script in `package.json` and while I guessed these files were included in some other repository's build process, a (admittedly cursory) search for the consumer didn't yield anything.
> Improve CM4 orientation instructions

- .github/ISSUE_TEMPLATE/config.yml
- similar to what we have for [core issues](https://github.com/home-assistant/core/blob/dev/.github/ISSUE_TEMPLATE/config.yml)
> Add an issue template chooser

- src/guides/reinstall-os.html
Link updated because it looks like it has changed
> Update page link

- src/faq.html
This SSD did not work. Just replaced the SSD with a different one, without changing anything else, made the installation pass without problems and as described.
> Update faq.html: adding incompatible Samsung SSD

- src/guides/use-serial-console-linux-macos.html
Debug procedure: fix incorrect step reference
- tiny style tweaks
> Debug procedure: fix incorrect step reference

- src/guides/about-multiprotocol.html
About multiprotocol: add update section
- aligning content with SkyConnect
> About multiprotocol: add update section

- src/guides/yellow-leds.html
- implements feedback from https://github.com/home-assistant/yellow.home-assistant.io/issues/239
> Document blue LED

- src/_includes/base.liquid
As per https://discord.com/channels/330944238910963714/887751499785072711/1284927132685963345
> base.liquid: Update #yellow to #hardware

- src/faq.html
- add section on Connectivity to improve structure and align with Green
> FAQ: add that there is no onboard Z-Wave or bluetooth

- src/documentation.html
- src/procedures/procedures.11tydata.yaml
- src/procedures/remove-cm4.html
- src/procedures/reseat-cm4.html
- video on cover opening needs to show a Yellow with a board already installed
> Remove CM4: update removal steps to apply also to CM5

- src/_includes/style.css
stops getting started from breaking the line
> Navbar: fix breakpoint

- src/documentation.html
- src/guides/reinstall-os.html
- add note to make it clear that the procedure to reinstall the OS is for CM4, not for CM5
> Reinstall OS procedure is for CM4

- src/documentation.html
- src/guides/flash-cm4-firmware.html
- src/procedures/procedures.11tydata.yaml
- src/procedures/reinstall-os-cm5.html
:shaking_face: :face_with_open_eyes_and_hand_over_mouth: :strawberry: :scream:
> fix typo in product name
